name: PickupArrows
main: me.exphc.PickupArrows.PickupArrows
version: 1.0
permissions:
    pickuparrows.*:
        children:
            pickuparrows.skeleton: true
        default: false
    pickuparrows.skeleton:
        description: Allows you to pickup arrows shot by nearby skeletons
        default: op

