name: PickupArrows
main: me.exphc.PickupArrows.PickupArrows
version: 1.2
permissions:
    pickuparrows.*:
        children:
            pickuparrows.allow: true
        default: false
    pickuparrows.allow:
        description: Allows you to pickup arrows you normally would not be able to
        default: false

