# For help please either refer to the bukkit dev page:
# http://dev.bukkit.org/bukkit-plugins/pickuparrows/
usePermissions: false
range: 10.0
pickupFrom:
  skeleton: true
  player: true
  other: false
  fire: false
useWorldGuard: false
useListAsBlacklist: false
regions: []