name: PickupArrows
main: de.dustplanet.pickuparrows.PickupArrows
description: Allows you to pickup arrows
version: ${project.version}-b${BUILD_NUMBER}
author: xGhOsTkiLLeRx
authors: [mushroomhostage]
website: http://dev.bukkit.org/bukkit-plugins/pickuparrows/
permissions:
  pickuparrows.*:
    children:
      pickuparrows.allow.*: true
    default: op
  pickuparrows.allow.*:
    default: op
softdepend: [WorldGuard]
