# For help please either refer to the
# forum thread: http://bit.ly/pathread
# or the bukkit dev page: http://bit.ly/papagedev
usePermissions: false
range: 10.0
pickupFrom:
  skeleton: true
  player: true
  other: false
  fire: false