name: PickupArrows
main: de.dustplanet.pickuparrows.PickupArrows
version: 2.0
permissions:
    pickuparrows.*:
        children:
            pickuparrows.allow: true
        default: op
    pickuparrows.allow:
        description: Allows you to pickup arrows you normally would not be able to
        default: op