name: PickupArrows
main: de.dustplanet.pickuparrows.PickupArrows
description: Allows you to pickup arrows
version: 2.0
author: xGhOsTkiLLeRx
authors: [mushroomhostage]
website: http://bit.ly/papagedev
website: http://bit.ly/pathread
permissions:
    pickuparrows.*:
        children:
            pickuparrows.allow: true
        default: op
    pickuparrows.allow:
        description: Allows you to pickup arrows you normally would not be able to
        default: op